# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Language options
language: node_js
node_js:
  - '0.10'
before_script:
  - npm install object-parser-cli@0.0.0 --global

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: hB35fYZW2iARrmZknWQHtzWvH8LGPiSqqiHxF/hBuXzLgJTuR+9VVfExeFPKPskQb+EcOhr0ucQ50KpTzWidzWILVPVJ7iehUkHheVsuNDeroBE4gs1VHnN+g+gKM8BrIc5dihO/oSYRmBlic5X7A1nm2lqNqYwQp3/m3RT+MfMCDbD2POcBSbTpTK0yIuhPKj+X1/oshTm2oKbhupVCHMtd1qOasfzK+1Ocy633dJRKthPZnHe7Rb3TiJCeYmDfyBp59Gw/2NJVqepBmoWlCQ25Xs0GsKkhMGM+G9ssP5icxOj10jDsDlRB2tOwrguOvT0ri/V41JVCcZrUF5Yyz2behv3MkCo2GPpYHKz+B5FpSG/ZcG9a3Vq+gTj2J7NXD2EsskS/70rVAGfw1EIzWjEVH/nIyXWqKaA2oSHgo843tQ3a6oW3CJV4DN4ACZe5ty9rlDUmoGXaxJyNYM36SZ9yfry1a7JTx9n+BDbSfUxaVa+gTJtv4lyiRMbPP4t6ySlq0CGjZhjRCIGQuy+0UicaLaPS+SJyKpJtTT6UzOIa3UjTKTRt9cHd8l5zG1W7cbWA6aj3JmsempMqCaA7mZlvCDGuu3sXI0HzAUKn/3lsqDkGbQ0GTSETcEddN5+mt13U2NttCg3f8PW8B8clwGY2xrdd646fTq/AFrfWjbA=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: wy3s/YWCEFXTkvhe7dAnLSVQWZYaO2wPJTtkF/ueCIL3/HRa0/hacLpNjrbCKgwGmo4chxn6Y0rbE/vUPSa8xqCk7ZvleaEcRjET3BPpPj06z214mxN5YrN/qxFu4AatsLLFtV3K9oYrziH8zZA0m0ONrOPQbnFLICrARxwOUf3kZPqD6dvmlTpKpW+rEx8Guqmt8H0oUp7xFzgkikwitU683UriDmWNozQ3f5G77wU3do2JDtz1cWNtjPXMF9SHA24ZYB6bKX24A+wCO3kA5m4gvb9AKGopzHc+ds1M52YQXdVIcHe4eGUiCBVCPHst0KuNWiAikeaTHcaufQXVvtRE57jOxCGgkLCnu0PoItWqREbZ7qjGAn8bmol8F2MNk114JIzicHys7190zAzbzPwofk+XQqFquvacuTLwBjuRucRZepD2GTm2n0J4AEGxTqNuhZofRiDrw1t6BXOwFiPcqBYcwI2VZPU1Kd2YobbiIepLToIMXTIKGNHPy2iwWL18SuDfxxKu31mpCJiBpszwyTj/yhTJmg14zCps5AQQ5RI+WGowCgYWLCBLZvtGxgI6oZLdW6Dy19OYqFBogteH5GHw0/11ldJ/LcrJPjTyXji6Pr29edQTZA/0Eh1OpiJj5UGTXcDWEqiRbOKaHZkc8I3SWY76EWNYScjoA4o=
